### PR TITLE
Add Gateway Load balancer to description

### PR DESCRIPTION
**Pull request by dontirun**
Gateway Load Balancers also use this for listeners, as [seen here](https://github.com/aws-samples/aws-gateway-load-balancer-code-samples/blob/main/aws-cloudformation/gwlb/GwlbWithTargetGroupAndListenerSample.yaml)

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dontirun** [comment]
Anything need to be changed here?

**Comment by swiercek** [comment]
This is service writer owned content. Leaving open.

**Comment by dontirun** [comment]
@swiercek what's the best way to raise this to the service writer? I don't know if solely leaving this open will do anything

**Comment by swiercek** [comment]
Hello @dontirun, 

I'm working on refreshing the Github repository for the CloudFormation user guide. Please rest assured that I'm going through each PR so that we can get in touch with the corresponding service writer to address this directly.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).

**Pull request closed without merging**
