### PR TITLE
Update aws-resource-applicationautoscaling-scalingpolicy.md

### PR DESCRIPTION
**Pull request by adclark1**
Per https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-auto-scaling.html, "Amazon ECS Service Auto Scaling supports the following types of scaling policies: Target Tracking Scaling Policies AND Step Scaling Policies." Therefore, the statement here ("For DynamoDB, only TargetTrackingScaling is supported. For any other service, only StepScaling is supported.") in the documentation is not entirely true, so I suggest we at least remove the second part of that statement.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by adclark1** [comment]
A couple things:

1. The new update now says "Amazon DynamoDB and Aurora for Amazon RDS only support TargetTrackingScaling. Any other service only supports StepScaling." This still isn't entirely true because ECS is another service that supports TargetTrackingScaling.

2. Why isn't the change reflected in the repo? The live page and repo don't match.

**Comment by AWSRandall** [comment]
@adclark1 - thanks for submitting!

The reason the GitHub repo fell behind the docs on our AWS website is because we were originally overwhelmed with PRs and couldn't keep up. We want to give credit to all the people who made requests before we refresh the GitHub repo, and to do that we need to merge all our open PRs. 

Could you please pull down the latest version of this .md file and submit your PR again? I'm sorry to ask this of you, but I want to make sure you get credit for the PR. 

Let me know if you have any questions, and thanks for your patience. We're almost finished closing all our open PRs, and then we'll get the GitHub repo back in sync with the AWS docs website.

Thanks again for using CloudFormation!

**Comment by adclark1** [comment]
I have pulled down the latest version and updated it to match the statement on the CLI docs here:

https://docs.aws.amazon.com/cli/latest/reference/application-autoscaling/put-scaling-policy.html

**Comment by ckesser** [comment]
@adclark1 I appreciate you making this update! Thanks for rebasing, I'll merge your request.

**Pull request merged**
