### PR TITLE
Removed unnecesary compleksity.

### PR DESCRIPTION
**Pull request by davidgatti**
*Issue #, if available:*

Hard to understand what dose random values are

*Description of changes:*

Removed unnecessary string that creates unnecessary confusion.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by davidgatti** [comment]
How many more years will it take for this PR to be merged?

**Comment by sasake615** [comment]
Thanks for your feedback. As you pointed out, the document should be using standard bucket placeholder names.

**Comment by davidgatti** [comment]
This is not a feedback, this is a PR either you merge it or close it ;) I see that you put the documentation on GitHub but have no idea how to use it.

**Comment by AWSRandall** [comment]
> 
> 
> This is not a feedback, this is a PR either you merge it or close it ;) I see that you put the documentation on GitHub but have no idea how to use it.

Thanks for creating the PR and also for giving us feedback on how we're doing. 

Apologies for taking a long time to get to this request. The CloudFormation repo in particular gets a lot of traffic, and we are doing our best to respond in a timely manner. We're continually onboarding new people to help us manage all these requests, and that also involves training. I'll take this back to the group and make sure we address what you've raised. 

We put our docs on GitHub to give customers one more way of providing feedback and making sure everything is up to date, and thanks again for helping improve the accuracy for everyone!

**Pull request merged**
