### PR TITLE
Update aws-resource-logs-destination.md

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Use native YAML for IAM policy, and explain why the name is mandatory.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
I reverted "Use native YAML for IAM policy" because `DestinationPolicy` requires a string, not object. Unfortunate :(.

I think it would be good to more explicitly call this out in its docs, as it doesn't match the approach used by most of the rest of CloudFormation, where IAM policies are supported as native objects.

**Comment by alexjurkiewicz** [comment]
ping

**Comment by ckesser** [comment]
I'm definitely going to merge your explanation of the DestinationName requirement. Thanks for adding some valuable context! However, I'm leaning toward keeping the DestinationPolicy description as-is; we explicitly state which data type each property accepts, so I think additionally stating which data types a property _doesn't_ accept might read as redundant rather than clarifying. If you have thoughts about this, we can always revisit in the comments here or in a new PR.

**Comment by alexjurkiewicz** [comment]
That makes sense to me. Thanks for your time today!! 🙇

**Pull request merged**
