### PR TITLE
Adding Valid Values for MatchingEventTypes

### PR DESCRIPTION
**Pull request by MaseratiPilot**
*Description of changes:*
Missing valid values for MatchingEventTypes

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by MaseratiPilot — COMMENTED** [review]
needs to be lower case - doesn't match configuration result query

**Comment by MaseratiPilot** [comment]
sorry the valid values should be:

      - bounce
      - click
      - complaint
      - delivery
      - open
      - reject
      - renderingFailure
      - send

I didn't figure this out until a ran the CFT and got an error that the values in all CAPS results in an error.

**Comment by MaseratiPilot** [comment]
Sorry closed by mistake

**Comment by julieso** [comment]
Thanks for your contribution. I am also in the process of adding descriptions for these values.

**Pull request merged**
