### PR TITLE
Change AWS::Events::Rule Target RoleArn property to 'Conditional'

### PR DESCRIPTION
**Pull request by LJArendse**
*Overview*

Currently the [AWS::Events::Rule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html) CloudFormation documentation lists the [RoleArn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-rolearn) as `Required: No`. However, for example when the target is a codebuild project, omitting the RoleArn property results in a CloudFormation CREATE_FAILED.

See error:
```
RoleArn is required for target arn:aws:codebuild:af-south-1:00000000:project/codebuild-project-1.
(Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException;
Request ID: XXXXXX-XXXX-XXXX-XXXX-XXXXXXXX; Proxy: null)
```
I believe that changing the `RoleArn` property from '_No_' to '_Conditional_' may more clearly indicate that the `RoleArn` may be a required property of the `AWS::Events::Rule` resource.

*Description of changes:*
- Change RoleArn Required property to 'Conditional'

I am happy to take any further guidance or suggestions.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

-------------------
:heavy_exclamation_mark: Please see my below [comment](https://github.com/awsdocs/aws-cloudformation-user-guide/pull/1178#issuecomment-1065010610) for the updated situation and change

### CODE REVIEW

**Comment by LJArendse** [comment]
I have looked deeper into the error message above:
> RoleArn is required for target arn:aws:codebuild:af-south-1:00000000:project/codebuild-project-1.
(Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException;
Request ID: XXXXXX-XXXX-XXXX-XXXX-XXXXXXXX; Proxy: null)

The `RoleArn` raised in the error appears to be referring to the `Resources.MyEventBridgeEventRule.Properties.Targets.RoleArn` of the Target (Case 1), not the `Resources.MyEventBridgeEventRule.Properties.RoleArn` resource property (Case 2). 

See `...Properties.Targets.RoleArn` (Case 1) vs. `...Properties.RoleArn` (Case 2) below:

`...Properties.Targets.RoleArn` (Case 1) [events-rule-target-rolearn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-target.html#cfn-events-rule-target-rolearn)
```
  MyEventBridgeEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: MyEventBridgeEventRule
      Description: EventBridge Event Rule Description
      Targets:
        - Arn: arn:aws:codebuild:af-south-1:000000000:project/c_build
          Id: unique-target-id-to-invoke
          RoleArn: arn:aws:iam::00000000:role/MyEventBridgeEventRuleTargetRole
      EventPattern: ...
      .
      .
      .
```

VS


`...Properties.RoleArn` (Case 2) [events-rule-rolearn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-rolearn)
```
  MyEventBridgeEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: MyEventBridgeEventRule
      Description: EventBridge Event Rule Description
      RoleArn: arn:aws:iam::00000000:role/MyEventBridgeEventRuleTargetRole
      EventPattern: ...
      .
      .
      .
```

What I find interesting is that the docs define 
[RoleArn  (Case 2)](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-rolearn) as:
> The Amazon Resource Name (ARN) of the role that is used for target invocation.

Which did not match the behaviour seen when adding the RoleArn, [events-rule-rolearn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-rolearn), property of the resource (Case 2) (As the above error remained). The error was only resolved after setting RoleArn, [events-rule-target-rolearn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-target.html#cfn-events-rule-target-rolearn), under the Target definition (Case 1). 


A possible suggestion, we could do, would be to maybe make the RoleArn usage more clear, [events-rule-rolearn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-rolearn), property of the resource (Case 2). I am also interested in understanding why adding [events-rule-rolearn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-rolearn) did not resolve the above error, since I was only defining one target to be triggered.

**Comment by rachfop** [comment]
This does look like an issue – to report issues with the resources and properties defined in the Resource Spec – you can open an issue here: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues 

That will allow the Event and CloudFormation devs to take a look at the underlining issue. I'll keep this doc PR open for kinclay to approve/merge/close. Thanks again for the deep dive.

**Comment by LJArendse** [comment]
@rachfop Awesome, I will open an issue, thanks for the help and support. 

@kinclay @rachfop Do you think the original commit e774fe48b8a6ddf390f30d664717e03d84f0e172 is still valid for the [events-rule-rolearn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-rolearn)? If yes, I am happy to redo that change as well.

**Comment by kinclay** [comment]
This is definitely needed. I merged the change.

**Pull request merged**
