### PR TITLE
Update the SourceAccessConfiguration property to include up-to-date properties

### PR DESCRIPTION
**Pull request by lewgordon**
*Description of changes:*

Adding additional valid properties for https://docs.aws.amazon.com/lambda/latest/dg/API_SourceAccessConfiguration.html.  During my testing today it seems like they should work now.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lewgordon** [comment]
I didn't update the description as I wasn't sure what would be required to change there.  It's probably worth noting for a few of the listed types the lambda function will need additional permissions.

**Comment by lewgordon** [comment]
Just noticed this is gone now @rachfop and @devlinbd2 , although I do think my documentation was still valid.  Do you know if I should have edited some other file?

**Comment by alivest** [comment]
@lewgordon Hello! Sorry about that, your PR is absolutely correct. I'll get it fixed and the weekly refresh cadence will pick up the changes.

**Comment by lewgordon** [comment]
@alivest no problem.  Thank you for the quick response!

**Pull request merged**
