### PR TITLE
Correcting inconsistent Update Behavior for DynamoDB SSESpecification

### PR DESCRIPTION
**Pull request by PatMyron**
… on different pages

The only property of DynamoDB SSESpecification says update will require replacement here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-ssespecification.html

*Issue #, if available:*

 https://github.com/awsdocs/aws-cloudformation-user-guide/issues/41

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by PatMyron** [comment]
Not sure why editing files through the Github UI online results in that, but if you hide whitespace changes, you can see the only line I actually changed:

screen shot 2018-07-06 at 10 42 35 pm

**Comment by ckesser** [comment]
@PatMyron Hey, thanks for submitting this. I checked the Resource Specification, which just complicated things further. The Resource Spec marks 'SSEEnabled' as requiring 'No Interruption'. I'm going to reach out to our product team and get back to you.

**Comment by PatMyron** [comment]
"Encryption at rest can be enabled only when you are creating a new DynamoDB table. Currently, you can't enable encryption at rest on an existing table. After encryption at rest is enabled, it can't be disabled."
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/EncryptionAtRest.html

**Comment by ckesser** [comment]
Superseded by #149

**Pull request closed without merging**
