### PR TITLE
Improve RedrivePolicy formatting

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mig281** [comment]
@alexjurkiewicz Alex, unfortunately this formatting is generated automatically for all AWS docs pushed to GitHub. At this time, even if I accept the changes, they'll be overwritten by the next push.

**Comment by alexjurkiewicz** [comment]
I thought the point was that you could take these changes and apply them to your internal copy?

Example:
https://github.com/awsdocs/aws-cloudformation-user-guide/pull/437
https://github.com/awsdocs/aws-cloudformation-user-guide/pull/436

**Comment by mig281** [comment]
@alexjurkiewicz Ordinarily yes, but any changes related to formatting are all automated and aren't controlled by the individual tech writers. I'd like you to know that I have opened an internal ticket about this for the doc build team and they will work on it on their end.

**Comment by alexjurkiewicz** [comment]
Got it, thanks for the explanation

**Pull request closed without merging**
