### PR TITLE
TTL is Long

### PR DESCRIPTION
**Pull request by maulik887**
As per this change updating Documentation https://github.com/aws-cloudformation/cfn-python-lint/pull/1417

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mikolajprzybysz** [comment]
You havent fixed it in the whole document

**Comment by maulik887** [comment]
I will revisit if I missed other references

**Comment by ckesser** [comment]
The "Type", "Required", "and "Update behavior" fields for each property are auto-generated from the [resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). I've submitted a ticket to correct this value in the resource spec. The [source documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html#cfn-route53-recordset-ttl) is updated after the specification is updated.

**Comment by maulik887** [comment]
@ckesser Are these resource specification come from an open source repo (I guess no)? Wondering how can community point out/suggest change in resource specification to fix the document error?

**Comment by anilkumarmyla** [comment]
> I've submitted a ticket to correct this value in the resource spec.

Any reference for the same and any updates on the ticket?

**Comment by anilkumarmyla** [comment]
Any update on this @ckesser

**Pull request closed without merging**
