### PR TITLE
Fix typo: ColumName -> ColumnName

### PR DESCRIPTION
**Pull request by o1ek**

### CODE REVIEW

**Comment by russherm** [comment]
Patrick,

This should be assigned to Alice Kupcik (akupcik@) as she is the Cassandra writer now. BTW – there are 16ish occurrences of ColumName in the CloudFormation docs for Cassandra. I put Alice on the Cc line.

Thanks,
Russ

**Comment by rachfop** [comment]
@russherm 
Thank you for the update, I will make sure to note that moving forward.

**Comment by russherm** [comment]
Thanks, I completed the required Github training and linked my account today.  I am now looking into fixing this typo in all its occurrences,  I haven’t worked on CloudFormation before so it might take a bit longer.

Thx. Alice

From: Herman, Russ <russherm@amazon.com>
Sent: Friday, April 24, 2020 1:49 PM
To: awsdocs/aws-cloudformation-user-guide <reply@reply.github.com>
Cc: Kupcik, Alice <akupcik@amazon.com>
Subject: RE: [awsdocs/aws-cloudformation-user-guide] Fix typo: ColumName -> ColumnName (#646)

Patrick,

This should be assigned to Alice Kupcik (akupcik@) as she is the Cassandra writer now. BTW – there are 16ish occurrences of ColumName in the CloudFormation docs for Cassandra. I put Alice on the Cc line.

Thanks,
Russ

**Comment by akupcik** [comment]
I completed the account setup, you should be able to assign to me now.

**Comment by rachfop** [comment]
@o1ek Thank you for your contribution. Your commit will be in the documentation shortly.

**Pull request merged**
