### PR TITLE
Fix references to MySQL in Postgres examples

### PR DESCRIPTION
**Pull request by AndrewO**
*Issue #, if available:*

*Description of changes:* Fix typos and references to MySQL in Postgres examples.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by randyurbano** [comment]
Thanks for your feedback on this topic in the Aurora documentation for CloudFormation. 

Creating a Global Database cluster for Aurora PostgreSQL
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-globalcluster.html#aws-resource-rds-globalcluster--examples--Creating_a_Global_Database_cluster_for_Aurora_PostgreSQL

Was your intention only to replace these lines:

Username for MySQL database access  >  Username for PostgreSQL database access

Password MySQL database access  >  Password for PostgreSQL database access

Your commit has changes to large chunks of content. If you only wanted to replace these lines, I can do that in the source files and update this documentation. In this case, I won't merge your pull request, but I will correct the documentation.

**Comment by AndrewO** [comment]
Hmm, I'm not sure why the diffs look like that... maybe it had something to do with using the edit in place form?

But yes, the main changes are corrections to the descriptions for the Postgres examples. Also, the word "for" is missing in the existing MySQL descriptions. Nothing major, just some typos I noticed as I was reading.

**Comment by randyurbano** [comment]
Okay, I'll make those changes without merging this pull request. Thanks again for your feedback. The RDS doc team appreciates it.

**Comment by AndrewO** [comment]
Sounds good!

**Comment by randyurbano** [comment]
The documentation is updated:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-globalcluster.html#aws-resource-rds-globalcluster--examples

**Pull request closed without merging**
