### PR TITLE
State and ExecutionRoleArn are required

### PR DESCRIPTION
**Pull request by fabiodouek**
*Issue #, if available:*

*Description of changes:*
State and ExecutionRoleArn are required. Minor change.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cmmeyer** [comment]
Hi @fabiodouek -- on what are you basing this change?  The CloudFormation resource specification and the underlying DLM API (https://docs.aws.amazon.com/dlm/latest/APIReference/API_LifecyclePolicy.html) also have these properties marked as `Required: No`.  Are you getting an error that contradicts this?

**Comment by fabiodouek** [comment]
Hi @cmmeyer , It seems that the link you've referenced is the data type.

I'm based on the CreateLifecyclePolicy API: https://docs.aws.amazon.com/dlm/latest/APIReference/API_CreateLifecyclePolicy.html , which mentions Role State and ExecutionRoleArn being required.

What prompted me to review the documentation, was because when I created the CloudFormation stack without defining those two parameters, I got an exception during the stack creation, complaining that those attributes were not defined.

I hope that this makes sense.

**Comment by cmmeyer** [comment]
Thanks for the clarification. It looks like we'll need to update both the docs and the spec for this one then.

**Comment by ckesser** [comment]
@fabiodouek, thanks for the fix! @cmmeyer, thanks for the approval! Merging.

**Pull request merged**
