### PR TITLE
Remove incorrect assertion about parameters

### PR DESCRIPTION
**Pull request by edenhochbaum**
You can define resources conditionally without a parameters section.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rjlohan** [comment]
Hi @edenhochbaum, thanks for this submission. While you're technically correct in this change, the docs are setup to outline what we determined to be the most useful path for Conditions. Namely; using input parameters to control runtime execution of a template. Without using Parameters, what use case would be satisfied by Conditions?

**Comment by edenhochbaum** [comment]
> Without using  Parameters, what use case would be satisfied by Conditions?

Typically, you'd be creating a resource conditioned on the value of a pseudo-parameter, such as AWS::Region.  For example, if I want to create a VPC in us-east-1 and no other regions, I wouldn't use a Parameters section.

Separately, I think updating technical documentation to make it "technically correct" is worth doing.  Just for pragmatic reasons, I think it's counter-productive to make a false statement in technical docs for pedagogical reasons.

**Comment by rjlohan** [comment]
That's a fair use-case, though I'd rather call this out more explicitly in the docs rather than hide this further. e.g; extend your changes to include some text around including template or pseudo-parameters. That would improve the docs beyond the technical accuracy.

**Comment by ckesser** [comment]
I'd like to merge this request with some modifications based on the above conversation:

"Depending on the entity you want to conditionally create or configure, you must include statements in the following template sections:
Parameters section
Define the inputs that you want your conditions to evaluate. The conditions evaluate to true or false based on the values of these input parameters. If you want your conditions to evaluate pseudo parameters, you don't need to define the pseudo parameters in this section; pseudo parameters are predefined by AWS CloudFormation."

Thanks for helping us clarify @edenhochbaum!

**Pull request merged**
