### PR TITLE
fix yaml syntax

### PR DESCRIPTION
**Pull request by timoschilling**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ckesser** [comment]
Closed #329 in favor of this PR, as the issue is present across all reference topics in our user guide. I'm in the process of fixing this.

**Comment by fatbasstard** [comment]
@ckesser Can you also look at the [`ZERO WIDTH NO-BREAK SPACE`]((https://www.fileformat.info/info/unicode/char/feff/index.htm)) character that in there at each property line?

**Comment by ckesser** [comment]
Looking into it now, thanks!

**Comment by ckesser** [comment]
Hi @timoschilling and @fatbasstard, 

Both the invisible character and YAML spacing issues have been fixed. I forgot to merge this PR before updating the markdown, so this file is conflicted now... @timoschilling please feel free to either resolve the conflicts so I can merge your contribution or close out the PR now that the doc source has been updated.

**Pull request closed without merging**
